# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Configuration for the "finished" page
# Configuración de la página de finalización para Atomic Linux
---
restartNowMode: user-checked
restartNowCommand: "systemctl -i reboot"
notifyOnFinished: false
