# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Configuration for partition module
# Configuración del módulo de particionamiento para Atomic Linux
---
efiSystemPartition:     "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
defaultFileSystemType:  "ext4"
availableFileSystemTypes:  ["ext4","ext3","btrfs","jfs","xfs","f2fs"]

lvm:
    enable: false