# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Removes a single user (with userdel) from the system.
# This is typically used in OEM setups or if the live user
# spills into the target system.
# Configuración de eliminación de usuario para Atomic Linux
---
# Username in the target system to be removed.
# Nombre de usuario en el sistema objetivo a eliminar.
username: liveuser
