# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Configuration for users module
# Configuración del módulo de usuarios para Atomic Linux
---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - wheel
    - audio

autologinGroup:  autologin
doAutologin:     true
sudoersGroup:    wheel
sudoersConfigureWithGroup: true
setRootPassword: true
doReusePassword: true
allowWeakPasswords: false
allowWeakPasswordsDefault: true

user:
  shell: /bin/bash
  forbidden_names: [ root ]

hostname:
  location: EtcFile
  writeHostsFile: true
  forbidden_names: [ localhost ]

presets:
    fullName:
        editable: true
    loginName:
        editable: true
