# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Configuration for the welcome module
# Configuración del módulo de bienvenida para Atomic Linux
---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    10
    requiredRam:        1.0
    internetCheckUrl:   http://example.com

    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen

    required:
        - storage
        - ram

    geoip:
        style:    "json"
        url:      "https://geoip.kde.org/v1/calamares"
        selector: ""
