# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Atomic Linux Calamares Configuration
# Configuración de Calamares para Atomic Linux
---
instances:
- id:       before
  module:   shellprocess
  config:   shellprocess-before.conf
- id:       final
  module:   shellprocess
  config:   shellprocess-final.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - removeuser
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@before
  - packages
  - shellprocess@final
  - preservefiles
  - umount
- show:
  - finished

branding: atomic
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
