TIMEOUT=5
GRAPHICS=yes

:Atomic Linux (Live)
    PROTOCOL=linux
    KERNEL_PATH=boot:///arch/boot/x86_64/vmlinuz-linux
    INITRD_PATH=boot:///arch/boot/x86_64/initramfs-linux.img
    CMDLINE=archisobasedir=arch archisolabel=ATOMIC_LINUX quiet splash
